config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :poems
  get '/favourites' => 'poems#favourites', as: :favourites
  get '/subscribed' => 'poems#subscribed', as: :subscribed
  get '/written' => 'poems#written', as: :written
  get '/line/:id/write_more' => 'poems#write_another_version', as: :write_another_version
  post '/poems/:poem_id/create_another_version' => 'poems#create_another_version', as: :create_another_version
  get '/poems/:id/subscribe' => 'poems#toggle_subscribe', as: :subscribe_poem
  get '/version/:id/like' => 'poems#toggle_like', as: :like_version
  get '/top/poems' => 'poems#best_poems', as: :best_poems
  resources :tags

  #api
  namespace :api do
      resources :sessions, only: [:create]
      resources :poems, only: [:index, :create, :show, :update, :destroy]
      resources :tags, only: [:index, :create, :show, :update, :destroy]
      resources :users, only: [:index, :show]
  end
end

app/models/poem.rb
class Poem < ApplicationRecord
  belongs_to :user
  has_one :first_line, class_name: 'Line', primary_key: 'first_line_id', foreign_key: 'id'
  has_many :subscribes
  has_and_belongs_to_many :tags, join_table: 'poems_tags'

  scope :most_observed, -> {where id: Subscribe.group("poem_id").order("count_user_id desc").count("user_id").keys.take(10)}

  def all_versions
    if self.stone_date < Time.now
      find_versions(self.first_line, []).uniq.sort_by{|version| version[:likes]}.reverse
    else
      find_versions(self.first_line, []).uniq
    end
  end

  def find_versions(line, versions)
    if line.next_lines.empty?
      [{poem: line.poem.map{|single_line| single_line.slice(:id, :content, :created_at).merge(user: single_line.user.slice(:id, :name))}, likes: line.likes.count}]
    else
      line.next_lines.each do |next_line|
        versions += find_versions(next_line, versions)
      end
      versions
    end
  end

  def max_likes
    find_versions(self.first_line, []).map{|version| version[:likes]}.max
  end

  def first_version
    last_line = self.first_line
    while !last_line.next_lines.empty?
      last_line = last_line.next_lines.first
    end
    {poem: last_line.poem.map{|single_line| single_line.slice(:id, :content, :created_at).merge(user: single_line.user.slice(:id, :name))}, likes: last_line.likes.count}
  end

  def best_version
    self.all_versions.max_by{|poem| poem[:likes] }
  end

  def save_if_has_lines(lines)
    if lines.empty?
      false
    else
      if self.save
        self.add_new_lines(lines)
      else
        false
      end
    end
  end

  def add_new_line(content, previous_line_id)
    new_line = Line.new
    new_line.content = content
    new_line.user = self.user
    new_line.previous_line_id = previous_line_id
    new_line.save!
    new_line.id
  end

  def add_new_lines(new_lines_hash)
    lines_content = new_lines_hash["lines"].split("\r\n")

    #for not first version but another ones
    first_line = new_lines_hash["first_line_id"]

    unless lines_content.empty?
      #first line
      previous_line_id = self.add_new_line(lines_content.shift, first_line)

      #for only first version but not another ones
      if first_line.nil?
        self.first_line_id = previous_line_id
        self.save!
      end

      #another lines
      lines_content.each do |content|
        previous_line_id = self.add_new_line(content, previous_line_id)
      end
    end
    true
  end

  def can_modify?(user)
    user.has_role? :admin or self.user.id == user.id
  end

  def toggle_subscribe(user)
    if user.subscribed_poems.include?(self)
      user.subscribed_poems.delete(self)
    else
      user.subscribed_poems << self
    end
  end

  def is_subscribed?(user)
    if Subscribe.where(poem_id: self.id).where(user_id: user.id).count > 0
      true
    else
      false
    end
  end

  def line_is_liked?(line_id, user)
    if Like.where(line_id: line_id).where(user_id: user.id).count > 0
      true
    else
      false
    end
  end
end

app/controllers/api/poems_controller.rb
class Api::PoemsController < Api::ApiController

  def index
    poems = Poem.all
    render json: Api::PoemSerializer.new(poems).serialized_json
  end

  def show
    poem = Poem.find(params[:id])
    render json: Api::PoemSerializer.new(poem).serialized_json
  end
end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :reader_only, only: [:index, :favourites, :subscribed, :show]
  before_action :writer_only, only: [:new, :create, :written]
  before_action :set_poem, only: [:edit, :update, :destroy, :show, :toggle_subscribe]
  before_action :can_modify, only: [:edit, :update, :destroy]

  def index
    @poems = Poem.all
  end

  def favourites
    @poems = current_user.favourite_lines.map { |line| line.poem_version }
  end

  def subscribed
    @poems = current_user.subscribed_poems
  end

  def written
    @poems = current_user.poems
  end

  def new
    @poem = Poem.new
  end

  def edit
  end

  def show
  end

  def create
    @poem = Poem.new(poem_params)
    @poem.user = current_user
    if @poem.save_if_has_lines(params.require(:content).permit!.to_hash)
      redirect_to poem_path(@poem), notice: 'Właśnie dodałeś nowy wiersz!'
    else
      redirect_to written_path, alert: 'Nie udało się utworzyć nowego wiersza.'
    end
  end

  def update
    if @poem.update_attributes(poem_params)
      redirect_to poem_path(@poem), notice: 'Wiersz został zaktualizowany'
    else
      redirect_to poem_path(@poem), alert: 'Nie udało się zaktualizować wiersza.'
    end
  end

  def destroy
    @poem.destroy
  end

  def write_another_version
    @poem = Line.find(params[:id]).poem_version
  end

  def create_another_version
    @poem = Poem.find(params[:poem_id])
    if @poem.stone_date > Time.now
      if @poem.add_new_lines(params.require(:content).permit!.to_hash)
        redirect_to poem_path(@poem), notice: 'Właśnie dodałeś nową wersję wiersza!'
      else
        redirect_to written_path, alert: 'Nie udało się utworzyć nowego wiersza.'
      end
    else
      redirect_to written_path, alert: 'Minął już okres skamienienia dla tego wiersza!.'
    end
  end

  def toggle_subscribe
    @poem.toggle_subscribe(current_user)
  end

  def toggle_like
    Line.find(params[:id]).toggle_like(current_user)
  end

  def best_poems
  end

  private
  def set_poem
    @poem = Poem.find(params[:id])
  end

  def poem_params
    params.require(:poem).permit(:title, :stone_date, tag_ids: [])
  end

  def can_modify
    unless @poem.can_modify?(current_user)
      redirect_to(root_path, :alert => "Brak dostępu, tylko dla administratorów!")
    end
  end
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/views/poems/_list.html.erb
<% poems.each do |poem| %>
    <div class="light-bg tag">
      <%= render(
              partial: 'poems/poem',
              locals: {poem: poem}
          ) %>
    </div>
<% end %>
<% if poems.empty? %>
 brak wierszy do wyświetlenia
<% end %>

app/views/poems/_poem.html.erb
<div id="poem_<%= poem.id %>" class="poem disappearing">
  <h4>Tytuł: <span class="poem-title"><%= poem.title %></span></h4>
  <p>
    <% poem.tags.each do |tag| %>
      <%= link_to '#' + tag.title, tag_path(tag), class: 'grey-text' %>
    <% end %>
  </p>
  <p class="grey-text">
    <span class="glyphicon glyphicon-time" aria-hidden="true"></span> Utworzony: <%= poem.created_at.strftime '%d.%m.%Y %H:%M' %><br>
    <span class="<% if poem.stone_date > Time.now %>green-text<% end %>"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Okres skamienienia: <%= poem.stone_date.strftime '%d.%m.%Y %H:%M' %></span><br>

    <% if current_user.nil? or !current_user.has_role? :reader %>
        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Obserwujących: <%= poem.subscribes.count %>
    <% else %>
        <%= link_to subscribe_poem_path(poem), remote: true, onclick: "toggle_value('subscribe_#{ poem.id }');" do %>
            <span <% if poem.is_subscribed?(current_user) %>class="orange-text"<% end %>><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> Obserwujących: <span id="subscribe_<%= poem.id %>"><%= poem.subscribes.count %></span></span>
        <% end %>
    <% end %>
  </p>
  <hr>

    <div class="versions">
        <% all_versions = poem.all_versions %>
        <% max_likes = poem.max_likes %>
        <% all_versions.each do |version| %>
            <div class="version<% if version[:likes] == max_likes and max_likes > 0 %> winner<% end %>">
              <p>
                <% version[:poem].each do |line| %>
                <span title="<%= line[:user][:name] %>">
                <% if current_user.nil? or !current_user.has_role? :writer or poem.stone_date < Time.now %>
                  <%= line[:content] %>
                <% else %>
                  <%= link_to line[:content], write_another_version_path(line[:id]) %>
                <% end %>
                </span><br>
                <% end %>
              </p>
              <p class="grey-text">
                <% if current_user.nil? or !current_user.has_role? :reader %>
                    <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Liczba polubień: <%= version[:likes] %>
                <% else %>
                    <%= link_to like_version_path(version[:poem].last[:id]), remote: true, onclick: "toggle_value('like_#{version[:poem].last[:id]}');" do %>
                        <span <% if poem.line_is_liked?(version[:poem].last[:id], current_user) %>class="orange-text"<% end %>><span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Liczba polubień: <span id="like_<%= version[:poem].last[:id] %>"><%= version[:likes] %></span></span>
                    <% end %>
                <% end %>
              </p>
            </div>
        <% end %>
    </div>

  <% if !current_user.nil? and poem.can_modify?(current_user) %>
    <%= link_to edit_poem_path(poem) do %>
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        Edytuj wiersz
    <% end %><br>
    <%= link_to poem_path(poem), method: :delete, onclick: "if(confirm('Jesteś pewien?')) hide_element('poem_#{poem.id}')" do %>
        <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
        Usuń wiersz
    <% end %>
  <% end %>
</div>

app/views/poems/_version.html.erb
<% poem = Poem.find(favourite_poem[:poem_id]) %>
<div class="light-bg tag">
  <div class="poem">
    <h4>Tytuł: <span class="poem-title"><%= link_to poem.title, poem_path(poem) %></span></h4>
    <p class="grey-text">
      <span class="glyphicon glyphicon-time" aria-hidden="true"></span> Utworzony: <%= poem.created_at.strftime '%d.%m.%Y %H:%M' %><br>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Okres skamienienia: <%= poem.stone_date.strftime '%d.%m.%Y %H:%M' %>
    </p>
    <hr>
    <div class="versions">
      <div class="version">
        <p>
          <% favourite_poem[:poem].each do |line| %>
              <span title="<%= line[:user][:name] %>">
                <% if current_user.nil? or !current_user.has_role? :writer %>
                  <%= line[:content] %>
                <% else %>
                  <%= link_to line[:content], write_another_version_path(line[:id]) %>
                <% end %>
              </span><br>
          <% end %>
        </p>

        <p class="grey-text">
          <% if current_user.nil? or !current_user.has_role? :reader %>
              <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Liczba polubień: <span id="like_<%= favourite_poem[:poem].last[:id] %>"><%= favourite_poem[:likes] %></span>
          <% else %>
              <%= link_to like_version_path(favourite_poem[:poem].last[:id]), onclick: "toggle_value(like_#{favourite_poem[:poem].last[:id]});" do %>
                  <span class="glyphicon glyphicon-thumbs-up" aria-hidden="true"></span> Liczba polubień: <span id="like_<%= favourite_poem[:poem].last[:id] %>"><%= favourite_poem[:likes] %></span>
              <% end %>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/poems/best_poems.html.erb
<h3>Top 10 najbardziej obserwowanych wierszy:</h3>

<%= render(
        partial: 'poems/list',
        locals: {poems: Poem.most_observed}
    ) %>

<hr>

<h3>Top 10 najbardziej polubianych wersji:</h3>

<% Line.most_liked.map{|line| line.poem_version}.each do |favourite_poem| %>
    <%= render(
            partial: 'poems/version',
            locals: {favourite_poem: favourite_poem}
        ) %>
<% end %>

app/views/poems/edit.html.erb
<div class="input-form">
  <h4>Edytujesz parametry wiersza: <span class="poem-title"><%= @poem.title %></span></h4>
</div>

<div class="input-form">
  <%= form_for(@poem, :url => {:action => "update"}, :html => {:role => 'form'}) do |f| %>
      <div class="form-group">

        <%= f.label 'Tytuł' %>
        <div class="input-field">
          <%= f.text_field :title, :autofocus => true, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <div>
          Okres skamienienia
        </div>
        <div class="input-field">
          <%= f.date_select :stone_date, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <div>
          Kategoria
        </div>
        <div class="input-field">
          <table>
            <% Tag.all.each do |tag| %>
                <tr>
                  <td>
                    <%= check_box_tag "poem[tag_ids][]", tag.id, @poem.tags.include?(tag) %><%= tag.title %>
                  </td>
                </tr>
            <% end %>
          </table>
        </div>
      </div>
      <%= f.submit 'Wprowadź zmiany' %>
  <% end %>
</div>

app/views/poems/favourites.html.erb
<h3>Polubione przez Ciebie wiersze</h3>

<% @poems.each do |favourite_poem| %>
    <%= render(
            partial: 'poems/version',
            locals: {favourite_poem: favourite_poem}
        ) %>
<% end %>
<% if @poems.empty? %>
    brak wierszy do wyświetlenia
<% end %>

app/views/poems/index.html.erb
<h3>Twórczość naszych użytkowników</h3>

<%= render(
        partial: 'poems/list',
        locals: {poems: @poems}
    ) %>

app/views/poems/new.html.erb
<div id="main-content" class="col-md-6">
  <h3>
    Nowe dzieło
  </h3>
  <hr>
  <div class="row">
    <%= form_for(@poem, :url => {:action => "create"}, :html => {:role => 'form'}) do |f| %>
        <div class="form-field">
          <div>
            Tytuł
          </div>
          <div class="input-field">
            <%= f.text_field :title, :autofocus => true, class: 'form-control' %>
          </div>
        </div>
        <div class="form-field">
          <div>
            Okres skamienienia
          </div>
          <div class="input-field">
            <%= f.date_select :stone_date, class: 'form-control' %>
          </div>
        </div>
        <div class="form-field">
          <div>
            Treść
          </div>
          <div class="input-field">
            <%= text_area :lines, class: 'form-control' %>
          </div>
        </div>
        <%= f.submit 'Utwórz' %>
    <% end %>
  </div>
</div>

app/views/poems/show.html.erb
<div class="light-bg tag">
  <%= render(
          partial: 'poems/poem',
          locals: {poem: @poem}
      ) %>
</div>

app/views/poems/write_another_version.html.erb
<% poem = Poem.find(@poem[:poem_id]) %>
<div class="input-form">
  <h4>Nowa wersja dla wiersza: <span class="poem-title"><%= poem.title %></span></h4>
</div>

<div class="light-bg tag">
  <div class="poem">
    <p class="grey-text">
      <span class="glyphicon glyphicon-time" aria-hidden="true"></span> Utworzony: <%= poem.created_at.strftime '%d.%m.%Y %H:%M' %><br>
      <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Okres skamienienia: <%= poem.stone_date.strftime '%d.%m.%Y %H:%M' %>
    </p>
    <hr>
    <div class="versions">
      <div class="version">
        <p>
          <% @poem[:poem].each do |line| %>
              <span title="<%= line[:user][:name] %>"><%= line[:content] %></span><br>
          <% end %>
        </p>

          <%= form_for(:poem, :url => create_another_version_path(poem), :html => {:role => 'form'}) do |f| %>
              <div class="form-group">
                <div>
                  Treść
                </div>
                <div class="input-field">
                  <%= fields_for :content do |w| %>
                      <%= w.text_area :lines, class: 'form-control' %>
                      <%= w.hidden_field :first_line_id, value: @poem[:poem].last[:id] %>
                  <% end %>
                </div>
              </div>
              <%= f.submit 'Utwórz' %>
          <% end %>

      </div>
    </div>
  </div>
</div>

app/views/poems/written.html.erb
<h3>Napisane przez Ciebie wiersze</h3>

<%= render(
        partial: 'poems/list',
        locals: {poems: @poems}
    ) %>