config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :poems
  get '/favourites' => 'poems#favourites', as: :favourites
  get '/subscribed' => 'poems#subscribed', as: :subscribed
  get '/written' => 'poems#written', as: :written
  get '/line/:id/write_more' => 'poems#write_another_version', as: :write_another_version
  post '/poems/:poem_id/create_another_version' => 'poems#create_another_version', as: :create_another_version
  get '/poems/:id/subscribe' => 'poems#toggle_subscribe', as: :subscribe_poem
  get '/version/:id/like' => 'poems#toggle_like', as: :like_version
  get '/top/poems' => 'poems#best_poems', as: :best_poems
  resources :tags

  #api
  namespace :api do
      resources :sessions, only: [:create]
      resources :poems, only: [:index, :create, :show, :update, :destroy]
      resources :tags, only: [:index, :create, :show, :update, :destroy]
      resources :users, only: [:index, :show]
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :poems, join_table: 'poems_tags'
end

app/controllers/api/tags_controller.rb
class Api::TagsController < Api::ApiController

  def index
    tags = Tag.all
    render json: Api::TagSerializer.new(tags).serialized_json
  end

  def show
    tag = Tag.find(params[:id])
    poems = tag.poems
    render json: Api::TagSerializer.new(tag).serialized_json
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :admin_only, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  def index
    @tags = Tag.all
  end

  def show
  end

  def new
    @tag = Tag.new
  end

  def edit
  end

  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Kategoria została dodana.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Kategoria została zaktualizowana.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Kategoria została usunięta.' }
      format.json { head :no_content }
    end
  end

  private
    def set_tag
      @tag = Tag.find(params[:id])
    end

    def tag_params
      params.require(:tag).permit(:title, :description)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<div class="input-form">
  <%= form_with(model: tag, local: true) do |form| %>
      <% if tag.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

            <ul>
              <% tag.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="form-group">
        <%= form.label 'Tytuł' %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label 'Opis' %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit 'Zatwierdź' %>
      </div>
  <% end %>
</div>

app/views/tags/edit.html.erb
<div class="input-form">
  <h1>Edycja kategorii: <%= link_to @tag.title, tag_path(@tag) %></h1>
</div>

<%= render 'form', tag: @tag %>

<%= link_to 'Powrót', tags_path %>

app/views/tags/index.html.erb
<h1>Kategorie</h1>

<% if !current_user.nil? and current_user.has_role? :admin %>
    <%= link_to new_tag_path do %>
      <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      Dodaj nową kategorię
    <% end %>
<% end %>

<% @tags.each do |tag| %>
<div id="tag_<%= tag.id %>" class="light-bg tag disappearing">
  <h4><%= link_to tag.title, tag_path(tag) %></h4>

  <% if !current_user.nil? and current_user.has_role? :admin %>
      <%= link_to edit_tag_path(tag) do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
          Edytuj kategorię
      <% end %><br>
      <%= link_to tag_path(tag), method: :delete, onclick: "if(confirm('Jesteś pewien?')) hide_element('tag_#{tag.id}')" do %>
          <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
          Usuń kategorię
      <% end %>
  <% end %>

  <p>
    <%= tag.description %>
  </p>

  <p>
    Liczba wierszy: <%= tag.poems.count %>
  </p>
</div>
<% end %>

app/views/tags/new.html.erb
<div class="input-form">
  <h1>Nowa kategoria</h1>
</div>

  <%= render 'form', tag: @tag %>

app/views/tags/show.html.erb
<h1>Kategoria: <%= @tag.title %></h1>
<hr>
<%= render(
        partial: 'poems/list',
        locals: {poems: @tag.poems}
    ) %>