config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#about'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users
  resources :poems
  get '/favourites' => 'poems#favourites', as: :favourites
  get '/subscribed' => 'poems#subscribed', as: :subscribed
  get '/written' => 'poems#written', as: :written
  get '/line/:id/write_more' => 'poems#write_another_version', as: :write_another_version
  post '/poems/:poem_id/create_another_version' => 'poems#create_another_version', as: :create_another_version
  get '/poems/:id/subscribe' => 'poems#toggle_subscribe', as: :subscribe_poem
  get '/version/:id/like' => 'poems#toggle_like', as: :like_version
  get '/top/poems' => 'poems#best_poems', as: :best_poems
  resources :tags

  #api
  namespace :api do
      resources :sessions, only: [:create]
      resources :poems, only: [:index, :create, :show, :update, :destroy]
      resources :tags, only: [:index, :create, :show, :update, :destroy]
      resources :users, only: [:index, :show]
  end
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <%= link_to 'Edycja konta', edit_user_registration_path %>
  <%= link_to 'Wylogowanie', destroy_user_session_path, :method=>'delete' %>
<% else %>
  <%= link_to 'Logowanie', new_user_session_path %>
  <%= link_to 'Rejestracja', new_user_registration_path %>
<% end %>

app/views/layouts/_navigation.html.erb
<div id="top-header">
  <div class="logo">
    Poe<span class="<% if user_signed_in? %>orange-bg<% else %>green-bg<% end %>">hub</span>
  </div>
  <div>
    <%= render 'layouts/nav_links_for_auth' %>
  </div>
</div>
<div id="menu">
  <%= render 'layouts/navigation_links' %>
</div>

app/views/layouts/_navigation_links.html.erb
<%= link_to "O serwisie", root_path %>
<%= link_to "Kategorie", tags_path %>
<%= link_to "Ranking wierszy", best_poems_path %>
<%= link_to "Ranking użytkowników", users_path %>

<% if user_signed_in? %>
<% if current_user.has_role? :writer %>
        <div id="writer-menu-link" class="dropdown">
          <%= link_to "Moja twórczość", "#", class: 'dropdown-toggle' %>
          <div id="writer-menu" class="dropdown-menu">
            <%= link_to "Napisz wiersz", new_poem_path %>
            <%= link_to "Napisane wiersze", written_path %>
          </div>
        </div>

<% end %>

<% if current_user.has_role? :reader %>
        <div id="reader-menu-link" class="dropdown">
          <%= link_to "Czytelnik", "#", class: 'dropdown-toggle' %>
          <div id="reader-menu" class="dropdown-menu">
            <%= link_to "Czytaj wiersze", poems_path %>
            <%= link_to "Obserwowane wiersze", subscribed_path %>
            <%= link_to "Polubione wiersze", favourites_path %>
          </div>
        </div>
<% end %>

<% end %>

app/views/layouts/_navigation_xs.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-light bg-inverse">
    <ul class="nav navbar-nav clearfix">
      <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
          &#9776;
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Twój profil", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_tag_list.html.erb
<% Tag.all.each do |tag| %>
  <span>
    <%= link_to tag.title, tag_path(tag) %>
  </span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PoeHub" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "PoeHub" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="tag-list">
      <script language="javascript">
        if (document.body.offsetWidth >= 768) {
          $('#tag-list').append('<%=j render "layouts/tag_list" %>');
        } else {
          $('#tag-list').hide();
        }
      </script>
    </div>
    <header>
      <script language="javascript">
        if (document.body.offsetWidth <= 768) {
          $('#menujs').append('<%=j render "layouts/navigation_xs" %>');
        } else {
          $('#menujs').append('<%=j render "layouts/navigation" %>');
        }
      </script>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>